FROM python:3.10-slim as builder

WORKDIR /app

ARG SYNC_DATABASE_URL
ARG ASYNC_DATABASE_URL
ARG JWT_TOKEN_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_REDIRECT_URI
ARG GOOGLE_APPLICATION_CREDENTIALS

RUN pip install poetry

COPY pyproject.toml poetry.lock README.md ./
RUN poetry config virtualenvs.create false && poetry install --only main --no-root

ENV SYNC_DATABASE_URL=$SYNC_DATABASE_URL
ENV ASYNC_DATABASE_URL=$ASYNC_DATABASE_URL
ENV JWT_TOKEN_SECRET=$JWT_TOKEN_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI
ENV GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS

COPY . .

EXPOSE 8000

CMD ["uvicorn", "chatbot.main:app", "--host", "0.0.0.0", "--port", "8000"]
