[tool.poetry]
name = "artisan-chatbot"
version = "0.1.0"
description = ""
authors = ["nomad-coder420 <saketmahajan0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.111.0"
uvicorn = "^0.34.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
